# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: XLA
logo_link_name: OpenXLA Project
repo_url: https://github.com/openxla/xla
repo_name: openxla/xla
edit_uri: edit/main/docs/
extra:
  homepage: https://scottamain.github.io/community

theme:
  name: material
  logo: website/assets/openxla-logo-lockup-white.svg
  logo_alt: OpenXLA
  favicon: website/assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  font:
    text: Noto
    code: Noto Sans Mono
  palette:
    # Light mode (scheme overrides in openxla.css)
    - scheme: default
      toggle:
        icon: material/brightness-6
        name: Switch to dark mode
    # Dark mode (scheme overrides in openxla.css)
    - scheme: slate
      toggle:
        icon: material/brightness-6
        name: Switch to light mode
  features:
    - content.code.copy    # Button to copy code snippets
    - content.action.edit  # Button to edit doc source
    - navigation.tabs      # Header tabs for nav items
    - navigation.top       # "Back to top" button
    - navigation.instant   # Ajax-style dynamic loading
    - toc.follow           # Scroll the TOC panel to follow the reader
  custom_dir: docs/website/overrides

extra_css:
  - website/stylesheets/openxla.css
extra_javascript:
  # MathJax
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Highlight.js
  - website/javascript/highlight.min.js
  - website/javascript/highlight-mlir.js

markdown_extensions:
  - admonition              # Notes, tips, caution, warnings, etc.
  - pymdownx.superfences    # Nesting code fences and custom fence formats
  - pymdownx.highlight:     # Syntax highlighting for code blocks
      use_pygments: false   #   Use highlight.js to get MLIR syntax support
  - pymdownx.inlinehilite   # And inline code (just in case): `#!python range()`
  - pymdownx.snippets:      # Include files/snippets: --8<-- 'README.md'
      check_paths: True     #   and fail the build if file not found
  - def_list                # Basic definition lists
  - pymdownx.tasklist:      # GitHub-style task lists checkboxes
      custom_checkbox: true #   and use fancier icons
  - pymdownx.arithmatex:    # Inline and block equations with MathJax
      generic: true         #   (required for some reason)
  - toc:                    # Settings for table of contents
      permalink: 'link'     # Use Material font's "link" icon; see openxla.css
      toc_depth: 3          # Max heading level to include in TOC

plugins:
  - search                         # Search bar
  - git-revision-date-localized:   # Show file Git revision history at bottom
      enable_creation_date: true   #   with both created and last-edited date

nav:
  - Home: index.md
  - Guides:
    - XLA architecture: architecture.md
    - Develop a new backend: developing_new_backend.md
    - Custom calls: custom_call.md
    - Aliasing: aliasing.md
    - Broadcasting: broadcasting.md
    - Shapes and layout: shapes.md
    - Tiled layout: tiled_layout.md
    - Operation semantics: operation_semantics.md
